version: '3.8'
services:
  oh-cli-dev:
    build: .
    volumes:
      - ./:/app
      - .openhands/settings.json:/root/.openhands/settings.json
      - .openhands/config.toml:/workspace/config.toml
      - ./workspace:/workspace

    tty: true
    working_dir: /workspace
