services:
  oh-cli-dev:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.48
    volumes:
      - ~/.openhands:/.openhands
      # config.tomlをマウントする設定。toml内の重複設定を削除したため、このマウントは問題ありません。
      - ./.openhands/config.toml:/root/.openhands/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
      # 新しい推奨形式でのワークスペースマウント
      - ./workspace:/workspace:rw
    environment:
      # ログ設定
      - LOG_ALL_EVENTS=true
      
      # ランタイム設定（新しい推奨形式）
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.48-nikolaik
      - RUNTIME_MOUNT=/workspace:/workspace:rw
      - SANDBOX_USER_ID=1000
      
      # API設定（こちらで設定を統一）
      - SEARCH_API_KEY=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
      
      # LLM設定（こちらで設定を統一）
      - LLM_MODEL=openai/claude-sonnet-4-20250514
      - LLM_API_KEY=sk-4XpD0aWTox5PE-iAdVWXDQ
      - LLM_BASE_URL=http://192.168.0.121:4001
      - LLM_CUSTOM_PROVIDER=openai
      
      # ランタイム設定
      - RUNTIME=docker
    ports:
      - "3003:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true
    pull_policy: always
