services:
  oh-cli-dev:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.48
    volumes:
      - ~/.openhands:/.openhands
      - ./.openhands/config.toml:/root/.openhands/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/app/workspace:rw
    env_file:
      - .env
    environment:
      # 環境変数はすべて.envファイルから読み込み
      - LOG_ALL_EVENTS=${LOG_ALL_EVENTS}
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE}
      # - RUNTIME_MOUNT=${RUNTIME_MOUNT}

      - SANDBOX_USER_ID=${SANDBOX_USER_ID}
      - SEARCH_API_KEY=${SEARCH_API_KEY}
      - RUNTIME=${RUNTIME}
      
    ports:
      - "3003:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true
    pull_policy: always
