name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract repo name
        id: repo
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Generate timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          echo "DATE_TAG=$(date -u +%Y%m%d)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/cli-action:latest
            ghcr.io/${{ env.REPO }}/cli-action:${{ env.TIMESTAMP }}
            ghcr.io/${{ env.REPO }}/cli-action:${{ env.DATE_TAG }}
            ghcr.io/${{ env.REPO }}/cli-action:${{ github.sha }}

      - name: Output image tags
        run: |
          echo "🐳 Published Docker images:"
          echo "  - ghcr.io/${{ env.REPO }}/cli-action:latest"
          echo "  - ghcr.io/${{ env.REPO }}/cli-action:${{ env.TIMESTAMP }}"
          echo "  - ghcr.io/${{ env.REPO }}/cli-action:${{ env.DATE_TAG }}"
          echo "  - ghcr.io/${{ env.REPO }}/cli-action:${{ github.sha }}"
